//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_DB_ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SicknessEntities : DbContext
    {
        public DB_SicknessEntities()
            : base("name=DB_SicknessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Sickness> Tbl_Sickness { get; set; }
        public virtual DbSet<Tbl_Symptoms> Tbl_Symptoms { get; set; }
        public virtual DbSet<Tbl_Treatment> Tbl_Treatment { get; set; }
        public virtual DbSet<Tbl_Medication> Tbl_Medication { get; set; }
        public virtual DbSet<Tbl_Effects> Tbl_Effects { get; set; }
    }
}
