//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_DB_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Medication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Medication()
        {
            this.Tbl_Effects = new HashSet<Tbl_Effects>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Tbl_TreatmentId { get; set; }
    
        public virtual Tbl_Treatment Tbl_Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Effects> Tbl_Effects { get; set; }
    }
}
