//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_DB_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sickness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sickness()
        {
            this.Tbl_Symptoms = new HashSet<Tbl_Symptoms>();
            this.Tbl_Treatment = new HashSet<Tbl_Treatment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Avr_Dur { get; set; }
        public string Leathality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Symptoms> Tbl_Symptoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Treatment> Tbl_Treatment { get; set; }
    }
}
