//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_DB_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Effects
    {
        public int Id { get; set; }
        public string Effect { get; set; }
        public int Tbl_MedicationId { get; set; }
    
        public virtual Tbl_Medication Tbl_Medication { get; set; }
    }
}
